export const data = [
  {
    Title: "Blade",
    Year: "1998",
    Rated: "R",
    Released: "21 Aug 1998",
    Runtime: "120 min",
    Genre: "Action, Horror, Sci-Fi",
    Director: "Stephen Norrington",
    Writer: "David S. Goyer",
    Actors: "Wesley Snipes, Stephen Dorff, Kris Kristofferson",
    Plot: "A half-vampire, half-mortal man becomes a protector of the mortal race, while slaying evil vampires.",
    Language: "English, Russian, Serbian",
    Country: "United States",
    Awards: "5 wins & 11 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYTU1ZTI0YjUtZGRlMS00MDU1LWFmZmItZWRiYTg5NTExMmRjXkEyXkFqcGdeQXVyMTUzMDg3MTQw._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.1/10" },
      { Source: "Rotten Tomatoes", Value: "58%" },
      { Source: "Metacritic", Value: "47/100" },
    ],
    Metascore: "47",
    imdbRating: "7.1",
    imdbVotes: "301,959",
    imdbID: "tt0120611",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$70,087,718",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Wonder Woman",
    Year: "2017",
    Rated: "PG-13",
    Released: "02 Jun 2017",
    Runtime: "141 min",
    Genre: "Action, Adventure, Fantasy",
    Director: "Patty Jenkins",
    Writer: "Allan Heinberg, Zack Snyder, Jason Fuchs",
    Actors: "Gal Gadot, Chris Pine, Robin Wright",
    Plot: "When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war, discovering her full powers and true destiny.",
    Language:
      "English, German, Dutch, Flemish, French, Spanish, Chinese, Greek, Ancient (to 1453), North American Indian",
    Country: "United States, China",
    Awards: "38 wins & 75 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTYzODQzYjQtNTczNC00MzZhLTg1ZWYtZDUxYmQ3ZTY4NzA1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.3/10" },
      { Source: "Rotten Tomatoes", Value: "93%" },
      { Source: "Metacritic", Value: "76/100" },
    ],
    Metascore: "76",
    imdbRating: "7.3",
    imdbVotes: "705,060",
    imdbID: "tt0451279",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$412,845,172",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Avengers",
    Year: "2012",
    Rated: "PG-13",
    Released: "04 May 2012",
    Runtime: "143 min",
    Genre: "Action, Sci-Fi",
    Director: "Joss Whedon",
    Writer: "Joss Whedon, Zak Penn",
    Actors: "Robert Downey Jr., Chris Evans, Scarlett Johansson",
    Plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
    Language: "English, Russian",
    Country: "United States",
    Awards: "Nominated for 1 Oscar. 39 wins & 81 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.0/10" },
      { Source: "Rotten Tomatoes", Value: "91%" },
      { Source: "Metacritic", Value: "69/100" },
    ],
    Metascore: "69",
    imdbRating: "8.0",
    imdbVotes: "1,468,717",
    imdbID: "tt0848228",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$623,357,910",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Lauf um Dein Leben - Vom Junkie zum Ironman",
    Year: "2008",
    Rated: "N/A",
    Released: "24 Apr 2008",
    Runtime: "96 min",
    Genre: "Biography, Drama, Sport",
    Director: "Adnan Köse",
    Writer: "Fritjof Hohagen, Adnan Köse",
    Actors: "Max Riemelt, Jasmin Schwiers, Uwe Ochsenknecht",
    Plot: "He lived the junkie's life as a heroin addict. Triathlon transformed him. Biopic of the record breaking Ironman Andreas Niedrig.",
    Language: "German",
    Country: "Germany",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDJhZjA5MWEtOTE5Yy00MWJiLTgwNjQtMDliOWI0NWJmZDZkXkEyXkFqcGdeQXVyMjY1ODY2Ng@@._V1_SX300.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "6.0/10" }],
    Metascore: "N/A",
    imdbRating: "6.0",
    imdbVotes: "261",
    imdbID: "tt0954542",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "StudioCanal",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Wrong Turn",
    Year: "2003",
    Rated: "R",
    Released: "30 May 2003",
    Runtime: "84 min",
    Genre: "Horror, Thriller",
    Director: "Rob Schmidt",
    Writer: "Alan B. McElroy",
    Actors: "Eliza Dushku, Jeremy Sisto, Emmanuelle Chriqui",
    Plot: "Chris and a group of five friends are left stranded deep in the middle of the woods after their cars collide. As they venture deeper into the woods, they face an uncertain and bloodcurdling fate.",
    Language: "English",
    Country: "Germany, United States",
    Awards: "3 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzc4MDhiMWUtNTY5Ny00NWY3LTk0ZmItM2NlYmRmOWQzNGVmXkEyXkFqcGdeQXVyNjc5NjEzNA@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "6.1/10" },
      { Source: "Rotten Tomatoes", Value: "41%" },
      { Source: "Metacritic", Value: "32/100" },
    ],
    Metascore: "32",
    imdbRating: "6.1",
    imdbVotes: "132,521",
    imdbID: "tt0295700",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$15,418,790",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];
